@startuml ドメインモデル図
left to right direction
title ドメインモデル図（ver: 3）

hide circle
hide methods

rectangle ユーザー集約 {
  class ユーザー #CBFDFF {
    プロファイルID
  }
  note left: ユーザー削除は論理削除とする

  class ポイント {
    ケーム結果ID
    ポイント数
  }
  note left: ユーザーが物理削除されたらポイントも削除する

  class ユーザーポイント {
    ユーザーID
    ポイントID
  }

  class プロファイル {
    名前
    アイコン
    性別
  }
  note right: - 名前は未記入不可・10文字以内\n- アイコンは未設定可能\n- 性別は男・女
}

rectangle ゲーム集約 {

  class ゲーム結果 #CBFDFF {
    ポイントID
    ラウンド数
    Bet数
  }
  note left: ユーザーが物理削除されたらゲーム結果からも削除する

  class ゲーム結果ユーザー {
    ゲームID
    ユーザーID
  }

  class プリセットユーザー {
    ユーザーID
    プリセットID
  }

  class プリセット {
    Bet数
    ラウンド数
  }
  note right: ユーザーが論理削除されたらプリセットからも削除する

  class ラウンド {
    ラウンド数
  }
  note right: ラウンドは1〜10まで

  class Bet {
    Bet数
  }
  note right: - 100単位\n- 10,000まで
}

ユーザー --> プロファイル

ゲーム結果ユーザー -- ゲーム結果
ゲーム結果ユーザー -- ユーザー
ゲーム結果 --> Bet
ゲーム結果 --> ラウンド

プリセットユーザー -- プリセット
プリセットユーザー -- ユーザー
プリセット --> Bet
プリセット --> ラウンド

ポイント -- ゲーム結果
ユーザーポイント -- ポイント
ユーザーポイント -- ユーザー

@enduml
