@startuml

title ゲーム開始

actor 操作ユーザー
boundary ゲーム画面
boundary ラウンド画面
control ゲーム開始ボタン
control 設定の検証
entity ユーザー
entity Bet
entity ラウンド

操作ユーザー --> ゲーム画面
ゲーム画面 --> ゲーム開始ボタン: ユーザー、Bet、ラウンドの設定をする
ゲーム開始ボタン --> 設定の検証
設定の検証 -- ユーザー
設定の検証 -- Bet
設定の検証 -- ラウンド
設定の検証 ..> ラウンド画面: <<ok>>
設定の検証 ..> ゲーム画面: <<ng: ユーザーが未選択または2人以下の場合>>
ラウンド画面 --> 操作ユーザー

@enduml
