@startuml

title ユーザーの削除

actor 操作ユーザー
boundary ユーザー一覧画面
boundary ユーザー詳細画面
boundary 削除ダイアログ
control ユーザーの選択
control ユーザー一覧の取得
control 削除ボタン
control はい
control いいえ
control ダイアログを閉じる
entity ユーザー

操作ユーザー --> ユーザー一覧画面
ユーザー一覧画面 --> ユーザーの選択
ユーザーの選択 --> ユーザー詳細画面: アイコン、名前、性別を詳細画面に反映
ユーザー詳細画面 --> 削除ボタン
削除ボタン --> 削除ダイアログ
削除ダイアログ --> はい
削除ダイアログ --> いいえ
はい --> ユーザー一覧画面
いいえ --> ダイアログを閉じる
ダイアログを閉じる --> ユーザー詳細画面

ユーザー一覧画面 --> ユーザー一覧の取得

ユーザー -- ユーザー一覧の取得: 参照
はい -- ユーザー: 削除

@enduml
