@startuml

title プリセットからの設定

actor 操作ユーザー
boundary ゲーム画面
boundary プリセット一覧画面
control プリセット一覧画面ボタン
control このプリセットで設定ボタン
control プリセット一覧の取得
control 選択したプリセットを表示
entity プリセット

操作ユーザー --> ゲーム画面
ゲーム画面 --> プリセット一覧画面ボタン
プリセット一覧画面ボタン --> プリセット一覧画面
プリセット一覧画面 --> このプリセットで設定ボタン
このプリセットで設定ボタン --> 選択したプリセットを表示
選択したプリセットを表示 --> ゲーム画面

プリセット一覧画面 -- プリセット一覧の取得
プリセット -- プリセット一覧の取得

@enduml
