@startuml

title プリセットの削除

actor 操作ユーザー
boundary ゲーム画面
boundary プリセット一覧画面
boundary プリセット詳細画面
control プリセット一覧画面ボタン
control プリセットの選択
control プリセット一覧の取得
control データの取得
control 削除ボタン
entity プリセット

操作ユーザー -- ゲーム画面
ゲーム画面 --> プリセット一覧画面ボタン
プリセット一覧画面ボタン --> プリセット一覧画面
プリセット一覧画面 --> プリセットの選択
プリセットの選択 --> プリセット詳細画面: ユーザー、Bet、ラウンドの表示
プリセット詳細画面 --> 削除ボタン
削除ボタン --> プリセット一覧画面
プリセット一覧画面 --> 操作ユーザー

プリセット一覧画面 -- プリセット一覧の取得
プリセット -- プリセット一覧の取得
プリセット -- 削除ボタン: 削除

@enduml
