@startuml
title 次のラウンドを開始

actor 操作ユーザー
boundary ラウンド画面
boundary 結果画面
control 次のラウンドへ
control カウントダウン
control 残りラウンド判定
entity ラウンド

操作ユーザー --> ラウンド画面
ラウンド画面 --> 次のラウンドへ
次のラウンドへ --> カウントダウン: 設定したラウンドのカウントダウンをする
カウントダウン --> 残りラウンド判定: 残りのラウンドを確認する
残りラウンド判定 ..> ラウンド画面: まだ残りラウンドがある場合
残りラウンド判定 ..> 結果画面: カウントがなくなった場合
結果画面 --> 操作ユーザー

カウントダウン -- ラウンド: ラウンドをカウントダウンしていく

@enduml
