@startuml
title ゲーム結果を見る

actor 操作ユーザー
boundary ラウンド画面
boundary ゲーム画面
boundary ゲーム結果画面
control 結果ボタン
control 終了
control もう一度
entity ゲーム結果

操作ユーザー --> ラウンド画面
ラウンド画面 --> 結果ボタン
結果ボタン -- ゲーム結果: 保存
結果ボタン --> ゲーム結果画面: 結果内容を表示する
ゲーム結果画面 --> 終了
終了 --> ゲーム画面
ゲーム結果画面 --> もう一度
もう一度 --> ラウンド画面: 同じ設定内容
ゲーム画面 --> 操作ユーザー

@enduml
