@startuml

title ユーザーデータの参照

actor 操作ユーザー
boundary ユーザー一覧画面
boundary ユーザー詳細画面
control ユーザーを選択
entity ユーザー

操作ユーザー --> ユーザー一覧画面
ユーザー詳細画面 --> 操作ユーザー
ユーザー一覧画面 --> ユーザーを選択
ユーザーを選択 --> ユーザー詳細画面
ユーザーを選択 -- ユーザー

@enduml
