@startuml
title ゲームの中断

actor 操作ユーザー
boundary ラウンド画面
boundary ゲーム画面
control ゲーム中断ボタン
control データの削除
entity ユーザー
entity ラウンド
entity Bet

操作ユーザー --> ラウンド画面
ラウンド画面 --> ゲーム中断ボタン
ゲーム中断ボタン --> データの削除
データの削除 --> ゲーム画面
ゲーム画面 --> 操作ユーザー

ユーザー -- データの削除
ラウンド -- データの削除
Bet -- データの削除

@enduml
