@startuml

title ユーザー登録

actor 操作ユーザー
boundary ユーザー一覧画面
boundary ユーザー登録画面
control ユーザー登録ボタン
control 登録ボタン
control ユーザー登録検証
entity ユーザー

操作ユーザー --> ユーザー一覧画面
ユーザー一覧画面 --> ユーザー登録ボタン
ユーザー登録ボタン --> ユーザー登録画面: アイコン、名前、性別の設定
ユーザー登録画面 --> 登録ボタン
登録ボタン --> ユーザー登録検証
ユーザー登録検証 ..> ユーザー一覧画面: <<ok>>
ユーザー登録検証 ..> ユーザー登録画面: <<ng: 名前が未記入または10文字以上の場合>>
ユーザー登録検証 -- ユーザー

@enduml
