@startuml
title プリセットの編集

actor 操作ユーザー
boundary プリセット一覧画面
boundary プリセット詳細画面
control プリセットの選択
control プリセット一覧の取得
control ユーザー選択
control Bet選択
control ラウンド選択
control 更新ボタン
entity プリセット
entity ユーザー
entity Bet
entity ラウンド

操作ユーザー --> プリセット一覧画面
プリセット一覧画面 --> プリセットの選択
プリセットの選択 --> プリセット詳細画面: 選択したプリセットのデータを詳細画面で表示する
プリセット詳細画面 --> ユーザー選択
プリセット詳細画面 --> Bet選択
プリセット詳細画面 --> ラウンド選択
プリセット詳細画面 --> 更新ボタン: ユーザー、Bet、ラウンドの編集
更新ボタン --> プリセット一覧画面

プリセット一覧画面 -- プリセット一覧の取得
プリセット -- プリセット一覧の取得: 参照
プリセット -- 更新ボタン: 更新

ユーザー選択 -- ユーザー
Bet選択 -- Bet
ラウンド選択 -- ラウンド

@enduml
