@startuml

title ユーザーの編集

actor 操作ユーザー
boundary ユーザー一覧画面
boundary ユーザー詳細画面
control ユーザーの選択
control ユーザー一覧の取得
control 更新ボタン
control 値の検証
entity ユーザー

操作ユーザー --> ユーザー一覧画面
ユーザー一覧画面 --> ユーザーの選択
ユーザーの選択 --> ユーザー詳細画面: 選択したユーザーデータを詳細画面に反映させる
ユーザー詳細画面 --> 更新ボタン: アイコン、名前、性別の編集
更新ボタン --> 値の検証
値の検証 ..> ユーザー一覧画面: <<ok>>
値の検証 ..> ユーザー詳細画面: <<ng: 名前が未記入または10文字以下の場合>>

ユーザー一覧画面 --> ユーザー一覧の取得

ユーザー -- ユーザー一覧の取得: 参照
値の検証 .. ユーザー: <<ok: 更新>>

@enduml
