@startuml

title プリセット登録

actor 操作ユーザー
boundary ゲーム画面
boundary 登録完了ダイアログ
control プリセット登録ボタン
control ダイアログを閉じる
control ユーザー選択
control Bet選択
control ラウンド選択
entity ユーザー
entity Bet
entity ラウンド
entity プリセット

操作ユーザー --> ゲーム画面
ゲーム画面 --> ユーザー選択
ゲーム画面 --> Bet選択
ゲーム画面 --> ラウンド選択
ゲーム画面 --> プリセット登録ボタン: ユーザー、Bet、ラウンドの設定をする
登録完了ダイアログ --> ダイアログを閉じる
ダイアログを閉じる --> ゲーム画面
プリセット登録ボタン --> 登録完了ダイアログ: プリセットを登録しました
プリセット -- プリセット登録ボタン: 設定してあるユーザー、Bet、ラウンドをプリセットに登録
ユーザー選択 -- ユーザー
Bet選択 -- Bet
ラウンド選択 -- ラウンド

@enduml
